version: '3'

services:
  overview:
    build: /
    depends_on:
      - 'redis'
      # - 'database'
    ports:
      - 3001:3001
    volumes:
      - .:/amenities
  redis:
    image: redis
    ports:
      - 6379:6379
  # database:
  #   image: postgres
